platform :ios, '7.0' 

target 'LiaoLiaoSleep' do

pod 'AFNetworking', '~> 3.1.0'
pod 'pop', '~> 1.0.9'
pod 'Masonry', '~> 1.0.2'

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’
# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
pod ‘UMengUShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
pod ‘UMengUShare/Social/ReducedSina'
# 无IDFA版SDK
pod 'UMengAnalytics-NO-IDFA'

end
